const Regions = [
    {
        region: 'Asia',
        paises: [
            "Afganistán",
            "Bangladesh",
            "Bután",
            "Brunei",
            "Kampuchea",
            "R.P.D. de Corea",
            "Timor Oriental",
            "India",
            "Indonesia",
            "Japón",
            "Laos",
            "Malasia",
            "Maldivas",
            "Mongolia",
            "Myanmar",
            "Nepal",
            "Pakistán",
            "Filipinas",
            "República de Corea",
            "Singapur",
            "Sri Lanka",
            "Tailandia",
            "Vietnam"
        ]
    },
    {
        region: 'Asia del Oeste y Africa del Norte',
        paises: [
            "Argelia",
            "Bahrein",
            "Egipto",
            "Irán",
            "Iraq",
            "Israel",
            "Jordania",
            "Kuwait",
            "Líbano",
            "Libia",
            "Mauritania",
            "Marruecos",
            "Omán",
            "Palestina",
            "Qatar",
            "Arabia Saudita",
            "Sudán",
            "Siria",
            "Túnez",
            "Turquía",
            "Emiratos Arabes Unidos",
            "Yemen"
        ]
    },
    {
        region: 'Africa',
        paises: [
            "Angola",
            "Benin",
            "Botswana",
            "Burundi",
            "Cabo Verde",
            "Comores",
            "República de Africa Central",
            "Camerún",
            "República del Congo",
            "Congo (Kinshasa)",
            "Costa de Marfil",
            "Jibuti",
            "Guinea Ecuatorial",
            "Eritrea",
            "Etiopía",
            "Gabón",
            "Gambia",
            "Ghana",
            "Guinea--Bissau",
            "Kenia",
            "Lesotho",
            "Liberia",
            "Madagascar",
            "Malí",
            "Mauricio",
            "Mozambique",
            "Namibia",
            "Niger",
            "Nigeria",
            "Ruanda",
            "Sao Tomé y Príncipe",
            "Senegal",
            "Seychelles",
            "Sierra Leona",
            "Somalia",
            "Africa del Sur",
            "Tanzania",
            "Togo",
            "Uganda",
            "Zambia",
            "Zimbabwe"
        ]
    },
    {
        region: 'Europa y Asia Central',
        paises: [
            "Armenia",
            "Azerbaiján",
            "Bielorusia",
            "Georgia",
            "Kazakstán",
            "Kirguizistán",
            "Moldavia",
            "Rusia",
            "Tadjikistán",
            "Turkmenistán",
            "Ucrania",
            "Uzbekistán"

        ]
    },
    {
        region: 'Europa',
        paises: [
            "Chipre",
            "Albania",
            "Bosnia y Herzegovina",
            "Bulgaria",
            "Croacia",
            "Checo",
            "Estonia",
            "Hungría",
            "Letonia",
            "Lituania",
            "Macedonia",
            "Polonia",
            "Rumania",
            "Eslovaquia",
            "Eslovenia",
            "Serbia y Montenegro",
            "Andorra",
            "Austria",
            "Bélgica",
            "Dinamarca",
            "Finlandia",
            "Francia",
            "Alemania",
            "Grecia",
            "Islandia",
            "Italia",
            "Irlanda",
            "Liechtenstein",
            "Luxemburgo",
            "Malta",
            "Mónaco",
            "Holanda",
            "Noruega",
            "Portugal",
            "España",
            "Suecia",
            "Suiza",
            "Gran Bretaña"
        ]
    },
    {
        region: 'América del Norte y Oceanía',
        paises: [
            "Australia",
            "Canadá",
            "Islas de Cook",
            "Fiji",
            "Kiribati",
            "Micronesie",
            "Nueva Zelanda",
            "Papúa Nueva Guinea",
            "Samoa",
            "Tonga",
            "Estados Unidos",
            "Vanuatu"
        ]
    },
    {
        region: 'América Latina y el Caribe',
        paises: [
            "Antigua y Barbuda",
            "Argentina",
            "Bahamas",
            "Barbados",
            "Bolivia",
            "Brasil",
            "Chile",
            "Colombia",
            "Costa Rica",
            "Cuba",
            "Dominica",
            "Ecuador",
            "El Salvador",
            "Granda",
            "Guyana",
            "Guatemala",
            "Honduras",
            "Jamaica",
            "México",
            "Panamá",
            "Perú",
            "República Dominicana",
            "Surinam",
            "Trinidad y Tobago",
            "Uruguay",
            "Venezuela"
        ]
    }
]


module.exports = Regions
